In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
elos=pd.read_csv(r'C:\Users\Asus\PredictingRatings\data\clean_elos.csv')
elos.head()

WhiteElo  BlackElo  MeanElos  DiffElos  SumElos
0      2354      2411      2382       -57     4765
1      1915      1999      1957       -84     3914
2      2446      2191      2318       255     4637
3      2168      2075      2121        93     4243
4      2437      2254      2345       183     4691

In [3]:
features=pd.read_csv(r'C:\Users\Asus\PredictingRatings\data\features.csv')
print(features.info())
print(features.shape)
features.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24255 entries, 0 to 24254
Columns: 233 entries, Result to InsufficientMaterial
dtypes: float64(111), int64(122)
memory usage: 43.1 MB
None
(24255, 233)


Result      NumMoves     MeanScore     ModeScore    FinalScore  \
count  24255.000000  24255.000000  24255.000000  24255.000000  24255.000000   
mean       0.544877     42.252690     30.881103     11.907442    111.901711   
std        0.417736     16.235593    233.709202    445.214702   2310.851869   
min        0.000000     10.000000  -2162.262500 -11447.000000 -12261.000000   
25%        0.000000     31.000000    -60.758665      0.000000   -362.000000   
50%        0.500000     40.000000     24.563636      0.000000      0.000000   
75%        1.000000     51.000000    123.987715     26.000000    546.500000   
max        1.000000    165.000000   2073.289256  11259.000000  12337.000000   

          FullMoves      MinScore      MaxScore   MedianScore      StdScore  \
count  24255.000000  24255.000000  24255.000000  24255.000000  24255.000000   
mean      83.967223   -794.591878    988.643950     68.913894    314.678490   
std       32.489872   2126.099646   2275.840558     64.170646    475.478471   
min       19.000000 -12348.000000    -51.000000      0.000000      7.795716   
25%       61.000000   -482.000000     67.000000     30.000000     61.336328   
50%       79.000000    -75.000000    156.000000     49.000000    145.621548   
75%      102.000000    -18.000000    700.000000     84.000000    291.317992   
max      329.000000     26.000000  12352.000000    784.000000   3962.575036   

               ...                   EndB         EndR     EndK   WhiteСhecks  \
count          ...           24255.000000  24255.00000  24255.0  24255.000000   
mean           ...               0.631293      1.03892      1.0      2.015584   
std            ...               0.676858      0.74847      0.0      2.874868   
min            ...               0.000000      0.00000      1.0      0.000000   
25%            ...               0.000000      0.00000      1.0      0.000000   
50%            ...               1.000000      1.00000      1.0      1.000000   
75%            ...               1.000000      2.00000      1.0      3.000000   
max            ...               2.000000      2.00000      1.0     71.000000   

       WhiteQueenCastle  BlackQueenCastle     Promotion     EnPassant  \
count      24255.000000      24255.000000  24255.000000  24255.000000   
mean           1.457308          0.910740      0.064069      0.061637   
std            4.179615          3.663225      0.291749      0.245589   
min            0.000000          0.000000      0.000000      0.000000   
25%            0.000000          0.000000      0.000000      0.000000   
50%            0.000000          0.000000      0.000000      0.000000   
75%            0.000000          0.000000      0.000000      0.000000   
max           35.000000         36.000000      4.000000      2.000000   

       CanClaimDraw  InsufficientMaterial  
count  24255.000000          24255.000000  
mean       0.035415              0.000783  
std        0.184831              0.027978  
min        0.000000              0.000000  
25%        0.000000              0.000000  
50%        0.000000              0.000000  
75%        0.000000              0.000000  
max        1.000000              1.000000  

[8 rows x 233 columns]

#### Поиск пропущенных значений

In [4]:
from sklearn.impute import MissingIndicator

indicator = MissingIndicator(missing_values=np.NaN)
indicator = indicator.fit_transform(features)

indicator

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [5]:
features.isnull().values.any()

False

#### Стандартизация
Стандартизация - это преобразование, которое центрирует данные путем удаления среднего значения каждого объекта, а затем масштабирует его путем деления (непостоянных) объектов на их стандартное отклонение . После стандартизации данных среднее значение будет равно нулю, а стандартное отклонение - одному.

Стандартизация может кардинально улучшить производительность моделей. Например, многие элементы, используемые в целевой функции алгоритма обучения (например, ядро RBF машин опорных векторов или регуляризаторы l1 и l2 линейных моделей), предполагают, что все объекты сосредоточены вокруг нуля и имеют дисперсию в том же порядке. Если у признака есть отклонение, которое на несколько порядков больше, чем у других, оно может доминировать в целевой функции и сделать оценщика неспособным учиться на других признаках правильно, как ожидалось.

В зависимости от ваших потребностей и данных, Sklearn предоставляет набор инструментов для масштабирования : StandardScaler , MinMaxScaler , MaxAbsScaler и RobustScaler .

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
fscale=scaler.fit_transform(features)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [7]:
len(fscale), len(fscale[0])

(24255, 233)

In [8]:
fscale[:5]

array([[-1.07432180e-01, -1.43223410e+00, -2.96688240e-02, ...,
        -2.50980631e-01, -1.91613355e-01, -2.79992455e-02],
       [-1.30438557e+00,  6.61973456e-01, -3.09399080e+00, ...,
        -2.50980631e-01, -1.91613355e-01, -2.79992455e-02],
       [ 1.08952121e+00, -2.00347304e-01,  7.85849638e-02, ...,
        -2.50980631e-01, -1.91613355e-01, -2.79992455e-02],
       [ 1.08952121e+00, -1.06266806e+00,  1.17738362e+00, ...,
        -2.50980631e-01, -1.91613355e-01, -2.79992455e-02],
       [-1.07432180e-01, -8.16290704e-01, -2.28992123e-04, ...,
        -2.50980631e-01, -1.91613355e-01, -2.79992455e-02]])

In [9]:
features_scale = pd.DataFrame(fscale)
features_scale.head()

0         1         2         3         4         5         6    \
0 -0.107432 -1.432234 -0.029669 -0.020007 -0.025057 -1.414846  0.361511   
1 -1.304386  0.661973 -3.093991  0.013685 -5.044089  0.678157 -5.056033   
2  1.089521 -0.200347  0.078585  0.042885  0.036394 -0.214447  0.359629   
3  1.089521 -1.062668  1.177384  0.013685  0.330231 -1.076272  0.378443   
4 -0.107432 -0.816291 -0.000229  0.013685 -0.053186 -0.799257  0.366685   

        7         8         9      ...          223       224  225       226  \
0 -0.402340 -0.754471 -0.606237    ...     0.544745  1.284087  0.0 -0.701119   
1 -0.393552 -0.092161  4.146337    ...    -0.932700 -0.052000  0.0  0.690277   
2 -0.347415 -0.497339 -0.553461    ...    -0.932700 -0.052000  0.0 -0.353270   
3 -0.031481  1.138957 -0.002976    ...     2.022190  1.284087  0.0 -0.701119   
4 -0.393113 -0.622009 -0.609573    ...    -0.932700 -0.052000  0.0 -0.701119   

        227       228       229       230       231       232  
0 -0.348678 -0.248622 -0.219609 -0.250981 -0.191613 -0.027999  
1 -0.348678 -0.248622 -0.219609 -0.250981 -0.191613 -0.027999  
2 -0.348678 -0.248622 -0.219609 -0.250981 -0.191613 -0.027999  
3 -0.348678 -0.248622 -0.219609 -0.250981 -0.191613 -0.027999  
4 -0.348678 -0.248622 -0.219609 -0.250981 -0.191613 -0.027999  

[5 rows x 233 columns]

In [10]:
from sklearn.preprocessing import RobustScaler
robust = RobustScaler(quantile_range = (0.1,0.9))
frobust=robust.fit_transform(features)

In [11]:
len(frobust), len(frobust[0])

(24255, 233)

In [12]:
frobust[:5]

array([[ 0.00000000e+00, -7.00000000e+00, -9.36157950e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.00000000e-01,  4.33333333e+00, -1.08881570e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.00000000e-01, -3.33333333e-01,  3.74955348e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.00000000e-01, -5.00000000e+00,  4.27585278e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -3.66666667e+00,  9.51541698e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [13]:
features_robust = pd.DataFrame(frobust)
features_robust.head()

0         1         2         3         4         5          6    \
0  0.0 -7.000000 -0.000936  0.000616  0.041667 -6.833333   0.056813   
1 -0.5  4.333333 -1.088816  0.003694 -8.907517  4.500000 -13.297761   
2  0.5 -0.333333  0.037496  0.006362  0.151236 -0.333333   0.052175   
3  0.5 -5.000000  0.427585  0.003694  0.675163 -5.000000   0.098553   
4  0.0 -3.666667  0.009515  0.003694 -0.008488 -3.500000   0.069567   

         7          8           9   ...   223  224  225  226  227  228  229  \
0  -4.677110  -4.471991  -28.719548 ...   0.0  1.0  0.0 -1.0  0.0  0.0  0.0   
1  -3.550096   2.196768  515.768981 ...  -1.0  0.0  0.0  3.0  0.0  0.0  0.0   
2   2.366731  -1.882944  -22.673115 ...  -1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  42.882903  14.592813   40.394373 ...   1.0  1.0  0.0 -1.0  0.0  0.0  0.0   
4  -3.493745  -3.138239  -29.101647 ...  -1.0  0.0  0.0 -1.0  0.0  0.0  0.0   

   230  231  232  
0  0.0  0.0  0.0  
1  0.0  0.0  0.0  
2  0.0  0.0  0.0  
3  0.0  0.0  0.0  
4  0.0  0.0  0.0  

[5 rows x 233 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
fminmax=minmax.fit_transform(features)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [15]:
fminmax[:5]

array([[0.5       , 0.05806452, 0.51615704, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.27741935, 0.34707742, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.18709677, 0.52213015, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.09677419, 0.58275839, ..., 0.        , 0.        ,
        0.        ],
       [0.5       , 0.12258065, 0.51778144, ..., 0.        , 0.        ,
        0.        ]])

In [16]:
features_minmax = pd.DataFrame(fminmax)
features_minmax.head()

0         1         2         3         4         5         6         7    \
0  0.5  0.058065  0.516157  0.504272  0.500650  0.061290  0.995798  0.009998   
1  0.0  0.277419  0.347077  0.504933  0.029149  0.280645  0.064975  0.011610   
2  1.0  0.187097  0.522130  0.505505  0.506423  0.187097  0.995474  0.020076   
3  1.0  0.096774  0.582758  0.504933  0.534027  0.096774  0.998707  0.078046   
4  0.5  0.122581  0.517781  0.504933  0.498008  0.125806  0.996687  0.011691   

        8         9   ...   223  224  225       226  227  228  229  230  231  \
0  0.026148  0.004712 ...   0.5  1.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   
1  0.080357  0.576097 ...   0.0  0.5  0.0  0.056338  0.0  0.0  0.0  0.0  0.0   
2  0.047194  0.011057 ...   0.0  0.5  0.0  0.014085  0.0  0.0  0.0  0.0  0.0   
3  0.181122  0.077240 ...   1.0  1.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   
4  0.036990  0.004311 ...   0.0  0.5  0.0  0.000000  0.0  0.0  0.0  0.0  0.0   

   232  
0  0.0  
1  0.0  
2  0.0  
3  0.0  
4  0.0  

[5 rows x 233 columns]

#### Нормализация
Нормализация - это процесс масштабирования отдельных образцов для получения единичной нормы . В основных терминах вам необходимо нормализовать данные, когда алгоритм прогнозирует на основе взвешенных отношений, сформированных между точками данных. Масштабирование входных данных в единичные нормы является обычной операцией для классификации или кластеризации текста .

Одно из ключевых различий между масштабированием (например, стандартизацией) и нормализацией заключается в том, что нормализация является построчной операцией , в то время как масштабирование является столбцовой операцией.
Хотя существует много других способов нормализации данных, sklearn предоставляет три нормы (значение, с которым сравниваются отдельные значения): l1 , l2 и макс . При создании нового экземпляра класса Normalizer вы можете указать желаемую норму в параметре norm .

Ниже формула для имеющихся норм обсуждаются и реализуются в коде Python - где результат представляет собой список знаменателей для каждого образца набора данных X  .

In [20]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer()
fnorm=normalizer.fit_transform(features)

In [21]:
features_norm = pd.DataFrame(fnorm)
features_norm.head()

0         1         2         3         4         5         6    \
0  0.000281  0.010694  0.013478  0.001689  0.030393  0.021388 -0.014634   
1  0.000000  0.000003 -0.000042  0.000001 -0.000707  0.000006 -0.000707   
2  0.000127  0.004959  0.006262  0.003942  0.024921  0.009790 -0.003814   
3  0.000006  0.000143  0.001751  0.000103  0.005005  0.000280  0.000057   
4  0.000218  0.012648  0.013445  0.007850 -0.004797  0.025296 -0.006542   

        7         8         9   ...        223           224           225  \
0  0.041087  0.011538  0.014877 ...   0.000563  1.125676e-03  5.628378e-04   
1  0.000006  0.000004  0.000140 ...   0.000000  6.121344e-08  6.121344e-08   
2  0.025176  0.004705  0.006551 ...   0.000000  1.271491e-04  1.271491e-04   
3  0.005245  0.000812  0.001792 ...   0.000011  1.143992e-05  5.719961e-06   
4  0.040997  0.012648  0.010836 ...   0.000000  4.361357e-04  4.361357e-04   

            226  227  228  229  230  231  232  
0  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  
1  2.448538e-07  0.0  0.0  0.0  0.0  0.0  0.0  
2  1.271491e-04  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 233 columns]

In [23]:
from sklearn.feature_selection import mutual_info_regression

print(mutual_info_regression(features,elos.SumElos))

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


KeyboardInterrupt: 